FROM buildpkg/centos:7

COPY el7-vault.repo /

RUN yum-config-manager --disable base,updates,extras && \
    yum-config-manager --add-repo=/el7-vault.repo && \
    yum clean all && \
    yum makecache && \
    yum -y update && \
    yum -y install epel-release && \
    git config --global --add safe.directory /build && \
    rm -f /el7-vault.repo

COPY start /

CMD [ "/start" ]
