FROM registry.gitlab.com/orange-opensource/gitlab-buildpkg/rockylinux:9

RUN dnf -y update && \
    dnf config-manager --enable crb && \
    dnf -y install epel-release && \
    git config --global --add safe.directory /build

COPY start /

CMD [ "/start" ]
